spring:
  application:
    name: api-businessengagements
  cache:
    cache-names: businessInformation,businessEngagements,legalIds,partyIds
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s
  main:
    banner-mode: 'off'
integration:
  bolagsverket:
    connectTimeout: PT5S
    readTimeout: PT15S
    ttl: PT15S
  party:
    connect-timeout: PT5S
    read-timeout: PT15S
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
