spring:
  application:
    name: api-businessengagements
  main:
    banner-mode: 'off'
integration:
  bolagsverket:
    connectTimeout: PT5S
    readTimeout: PT15S
    ttl: PT15S
  party:
    connect-timeout: PT5S
    read-timeout: PT15S
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
# Cache properties
appconfig:
  cache:
    enabled: true
    expire-after-write: PT5M
    maximum-size: 100
