<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schema.bolagsverket.se/ssbtgu/v2"
				  xmlns:gu="http://schema.bolagsverket.se/ssbtgu/v2/grundlaggandeuppgifter"
				  xmlns:sf="http://schema.bolagsverket.se/ssbtgu/v2/servicefel"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:xs="http://www.w3.org/2001/XMLSchema"
				  targetNamespace="http://schema.bolagsverket.se/ssbtgu/v2">
	<wsdl:documentation>SSBTGU version 2.5.0 (ssbt-schema build version 1.5.7)</wsdl:documentation>

	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://schema.bolagsverket.se/ssbtgu/v2/grundlaggandeuppgifter"
					   schemaLocation="schema/ssbtgu/GrundlaggandeUppgifter.xsd"/>
			<xs:import namespace="http://schema.bolagsverket.se/ssbtgu/v2/servicefel"
					   schemaLocation="schema/ssbtgu/Servicefel.xsd"/>
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="GrundlaggandeUppgifterBegaran">
		<wsdl:part name="Message" element="gu:GrundlaggandeUppgifterBegaran"/>
	</wsdl:message>
	<wsdl:message name="GrundlaggandeUppgifterSvar">
		<wsdl:part name="Message" element="gu:GrundlaggandeUppgifterSvar"/>
	</wsdl:message>
	<wsdl:message name="ServicefelException">
		<wsdl:part name="Message" element="sf:Servicefel"/>
	</wsdl:message>

	<wsdl:portType name="SsbtguService">
		<wsdl:operation name="GetForetagsuppgifter">
			<wsdl:input message="GrundlaggandeUppgifterBegaran"/>
			<wsdl:output message="GrundlaggandeUppgifterSvar"/>
			<wsdl:fault name="Fault" message="ServicefelException"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="SsbtguServiceHttpBinding" type="SsbtguService">
		<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetForetagsuppgifter">
			<wsdlsoap:operation soapAction="urn:GetForetagsuppgifter" style="document"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault">
				<wsdlsoap:fault name="Fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="SsbtguServicePorts">
		<wsdl:port name="SsbtguService" binding="SsbtguServiceHttpBinding">
			<wsdlsoap:address location="https://serviceadress"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
